// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jQuery(function() {
    var ListView, list_view, _ref;

    ListView = (function(_super) {
      __extends(ListView, _super);

      function ListView() {
        _ref = ListView.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      ListView.prototype.el = $('body');

      ListView.prototype.initialize = function() {
        _.bindAll(this);
        this.counter = 0;
        return this.render();
      };

      ListView.prototype.render = function() {
        console.log(this.counter);
        $(this.el).append('<button>Add List Item</button>');
        return $(this.el).append('<ul></ul>');
      };

      ListView.prototype.addItem = function() {
        this.counter++;
        return $('ul').append("<li>Hello, Backbone " + this.counter + "!</li>");
      };

      ListView.prototype.showCounter = function() {
        this.counter++;
        return console.log(this.counter);
      };

      ListView.prototype.events = {
        'click button': 'addCounter'
      };

      return ListView;

    })(Backbone.View);
    return list_view = new ListView;
  });

}).call(this);
